spring:
  profiles:
    active: local
  datasource:
    auth:
      type: com.zaxxer.hikari.HikariDataSource
      pool-name: hikaricp-auth
      driver-class-name: com.mysql.cj.jdbc.Driver
      hikari:
        connection-test-query: SELECT 1
        maximum-pool-size: 5
        idle-timeout: 30000
        minimum-idle: 2
    iam:
      type: com.zaxxer.hikari.HikariDataSource
      pool-name: hikaricp-iam
      driver-class-name: com.mysql.cj.jdbc.Driver
      hikari:
        connection-test-query: SELECT 1
        maximum-pool-size: 5
        idle-timeout: 30000
        minimum-idle: 2
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
  liquibase:
    change-log: classpath:/db/changelog-master.xml
  mvc:
    hiddenmethod:
      filter:
        enabled: true

security.oauth2:
  jwt:
    key-pair:
      store-pass: ${JWT_KEYPAIR_STOREPASS:Test1234}
      alias: ${JWT_KEYPAIR_ALIAS:internal-certs}
      file-path: ${JWT_KEYPAIR_PATH:key-files/keystore.p12}
  resource:
    token-info-uri: ${SECURITY_OAUTH2_TOKEN_URL:http://localhost:8044/oauth/check_token}
    verifier-key.file-path: ${SECURITY_OAUTH2_VERIFIER_KEY_PATH:publicKey.pem}
  client:
    client-id: ${SECURITY_OAUTH2_CLIENT_ID:client_2}
    client-secret: ${SECURITY_OAUTH2_CLIENT_SECRET:123456}
