apiVersion: v1
kind: ConfigMap
metadata:
  name: order-service
  labels:
    app: order-service
data:
  application-k8s.yaml: |-
    spring:
      datasource:
        url: jdbc:mysql://192.168.179.1:3306/order?charset=utf8
      data:
        redis:
            host: redis-headless.default.svc.it-meta.space
            port: 6379