apiVersion: v1
kind: Service
metadata:
  labels:
    app: mysql
  name: mysql-service
spec:
  ports:
    - port: 3306
      name: mysql
      protocol: TCP
      targetPort: 3306
  selector:
    app: mysql
  type: LoadBalancer

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: mysql
  name: mysql-headless
spec:
  ports:
    - port: 3306
      name: mysql
      protocol: TCP
      targetPort: 3306
  selector:
    app: mysql
  clusterIP: None