apiVersion: v1
kind: Service
metadata:
  labels:
    app: redis
  name: redis-headless
spec:
  ports:
    - port: 6379
      name: redis
      protocol: TCP
      targetPort: 6379
  selector:
    app: redis
  clusterIP: None

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: redis
  name: redis-service
spec:
  ports:
    - port: 6379
      name: redis
      protocol: TCP
      targetPort: 6379
  selector:
    app: redis
  type: LoadBalancer
