spring:
  application:
    name: user-service
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      auto-commit: false
      connection-test-query: SELECT 1
      maximum-pool-size: 5
      idle-timeout: 30000
      minimum-idle: 2
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
  liquibase:
    change-log: classpath:db/changeset-master.xml
  data:
    redis:
      lettuce:
        pool:
          max-active: 3
          max-idle: 2
          min-idle: 1
          max-wait: 10000
      client-type: lettuce

auth:
  jwt:
    rsa-key-path: ${JWT_KEY_PATH:rsa-20221017.key}
    #    key-pair:
    #      kid: ${JWT_KEYSTORE_KID:internal-certs}
    #      store-pass: ${JWT_KEYSTORE_PASSWORD:Test1234}
    #      store-file-path: ${JWT_KEYSTORE_PATH:keystore.p12}
    time-to-live: 3600   # seconds
  sms-code:
    time-to-live: 5     # minutes

logging:
  level:
    root: info
    com.zaxxer.hikari.HikariConfig: debug
    org.akj.springboot: debug
    org.springframework.cloud: debug
server:
  port: 8080

