spring:
  application:
    name: order-service
  data:
    redis:
      lettuce:
        pool:
          max-active: 3
          max-idle: 2
          min-idle: 1
          max-wait: 10000
      client-type: lettuce
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://192.168.179.1:3306/order?charset=utf8
    hikari:
      auto-commit: false
      connection-test-query: SELECT 1
      maximum-pool-size: 5
      idle-timeout: 30000
      minimum-idle: 2
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
  liquibase:
    change-log: classpath:db/changeset-master.xml
auth:
  jwt:
    rsa-key-path: ${JWT_KEY_PATH:key-files/rsa-20221017.pem}

logging:
  level:
    root: info
    org.akj.springboot: debug
    org.springframework.cloud.kubernetes: debug

