apiVersion: v1
kind: ConfigMap
metadata:
  name: user-service-client-test
  labels:
    app: user-service-client-test
data:
  application.yaml: |-
    spring:
      config:
        activate:
          on-profile: k8s
      redis:
        host: redis-headless.default.svc.it-meta.space
        port: 6379