apiVersion: v1
kind: Secret
metadata:
  name: db-secret
type: Opaque
data:
#  spring.datasource.username: jamie
  spring.datasource.username: amFtaWU=
#  spring.datasource.password: Test1234
  spring.datasource.password: VGVzdDEyMzQ=
